# Generated by Django 5.2 on 2026-01-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
